package pl.inteca.credit.exception;

/**
 * Custom exception defined to distinguish ones generated by this app from actual errors
 */
public class CreditException extends Exception {
    public CreditException(String message) {
        super(message);
    }
}
